import Route from '@ember/routing/route';

export default class StyleguideIconsRoute extends Route {
  model() {
    return [
        'add',
        'alert-triangle',
        'arrow-down',
        'arrow-left',
        'arrow-right',
        'arrow-up',
        'bin',
        'bold',
        'calendar',
        'check',
        'chevron-left',
        'chevron-right',
        'cross',
        'document',
        'documents',
        'github',
        'hierarchal-back',
        'indent',
        'info-circle',
        'italic',
        'login',
        'logout',
        'manual',
        'message',
        'nav-down',
        'nav-left',
        'nav-right',
        'nav-up-down',
        'nav-up',
        'ordered-list',
        'pencil',
        'question-circle',
        'redo',
        'renew',
        'reverse-indent',
        'search-folder',
        'search',
        'sitemap',
        'strikethrough',
        'switch',
        'underlined',
        'unordered-list',
        'user-fill',
        'user-popup',
        'user',
        'users'
    ]
  }
}

